### ISSUE TITLE
Send rider contact details to driver only AFTER a match has been confirmed

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/backend#105]
Driver currently receives contact details for all proposed riders. Instead, they should only receive these details once they have confirmed the match. The street/apartment number should also be separated from the street name (issue #254 on the front end), so it can be sent along with the rest of the contact details.

This is for data protection and safety reasons. The driver can always cancel a match if it doesn't work for some reason.

In the notification above "If you do not wish to..." add "We will send you the rider's full address and contact details if you accept the match"

**Comment by dmilet** [comment]
hmm. How is the driver supposed to contact a proposed rider to confirm if the information is correct, prior to accepting.
Should drivers accept matches before confirming the details with the rider ?

**Comment by sasjkia** [comment]
@dmilet I understand your concern but the good thing is that the ride cancellation feature works well and I've tested several times to ensure that the rider can go back into the pool and get matched again. So now it's a case of ensuring the UX makes the process clear.

We need to avoid sending out the full address and contact details of potentially vulnerable people to a whole pool of drivers. At least if people have to accept first, we know who has the details. I can't really think of another solution and I don't think this change is going to prevent people from using the service.

**Comment by dmilet** [comment]
Do I remove 
- address
- phone number 
- email address

Anything else?
Please confirm
Thanks

**Comment by sasjkia** [comment]
Keep address but remove street number. Does this require it be a separate entry field on the front end?

Remove rest pls.

**Comment by dmilet** [comment]
Yes we don't currently  separate street name and number 
I'll remove the entire address for new

**Comment by sasjkia** [comment]
Best to pause on removing the address; there's a frontend PR pending that will separate the street number from the name

**Comment by dmilet** [comment]
Not sure how it's going to be implemented. I never had to split house number and street name on any form I had to fill in. Do we really want to ask our users to do that?

**Comment by sasjkia** [comment]
@dmilet it's not too uncommon to have multiple address lines. We can ask Tino, who has 10 years of US experience, for some suggestions.

Alternatively, is there a way to strip out any numbers in that field on the database side?

**Comment by dmilet** [comment]
See the usual format for addresses
http://www.bitboost.com/ref/international-address-formats/united_states/

I have never seen a web site that asks to split house number from street name, they're always on the same line

**Comment by sasjkia** [comment]
Are you able to hide numbers from the database side?

If not, my consideration is rider safety above all here; I think there are UX solutions to avoid confusion/form abandonment.

**Comment by dmilet** [comment]
I think it's too complicated to hide the numbers from the back end
5th avenue 
becomes
5 avenue

and god knows what else

If safety is your concern, let's just hide everything but the zip code

**Comment by sasjkia** [comment]
I'd considered it but it seems that zip codes are quite big in places

**Comment by dmilet** [comment]
so the process is:
1. driver accepts proposed match, based on zip code (remember we calculate distances based on zip codes only, that is a very rough estimation of the distances anyway)
2. driver gets full contact info
3. driver calls/emails rider to confirm in person
4. driver may decide to cancel the match if too far not not suitable
