### ISSUE TITLE
In test environment, it is not possible to log into the self-service portal

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/backend#106]
Entering the phone number and clicking the login button doesn't result in any change on the page

**Comment by dmilet** [comment]
@sasjkia it works for me.
this is the self-service page I'm using
http://richardwestenra.com/voteamerica.github.io/self-service/

I probably should update the notifications to use different self-service URLs for live and test service

**Comment by jkbits1** [comment]
@sasjkia @dmilet this is due to https://github.com/voteamerica/voteamerica.github.io/issues/273 and will be fixed when https://github.com/voteamerica/voteamerica.github.io/pull/274 is merged

**Comment by sasjkia** [comment]
@dmilet when i click on the link on the confirmation page, and the links in the notifications, i'm redirected to the live site, which is why it doesn't work.

**Comment by dmilet** [comment]
@sasjkia 
confirmation page: this needs merge on the front end and deployment on the test site. Not sure when Jon or Richard are planning to merge that one.
notfications : can you please forward an example of such email? it is recent ?

**Comment by sasjkia** [comment]
@dmilet notifications are fine now :)

**Comment by richardwestenra** [comment]
@sasjkia @jkbits1 This issue should be fixed now that https://github.com/voteamerica/voteamerica.github.io/pull/274 has been merged.

**Comment by jkbits1** [comment]
@sasjkia I'm closing this as there have been patches and no comments since then
