### ISSUE TITLE
Forms not redirecting to confirmation page after signup

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/backend#107]
- [ ] Rider and driver signups no longer redirects to confirmation page after submission. Shows blank page with UUID instead.

- [ ] Ditto for confirmation page when driver has confirmed a match, rider has cancelled a match, etc

**Comment by sasjkia** [comment]
Not sure if this is a frontend or back

**Comment by dmilet** [comment]
I think it's related to how the test page is deployed.
There is no redirect issue on live site, or on a local test site

**Comment by sasjkia** [comment]
Alas -I'm also having trouble with the live site

**Comment by jkbits1** [comment]
@sasjkia thanks for info - this duplicates https://github.com/voteamerica/backend/issues/103 but provides extra useful info 👍
