### ISSUE TITLE
Rider and Driver self-service won't allow login

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/backend#110]
Error message:

"No Ride Request found for those parameters"
"No Drive Offer found for those parameters"

**Comment by dmilet** [comment]
@sasjkia @jkbits1 I believe this works. Can you please confirm and close?

**Comment by jkbits1** [comment]
@sasjkia @dmilet see my comment in https://github.com/voteamerica/backend/issues/106#issuecomment-299663638

**Comment by richardwestenra** [comment]
@sasjkia @jkbits1 This issue should be fixed now that https://github.com/voteamerica/voteamerica.github.io/pull/274 has been merged. @sasjkia Can you please confirm?
