### ISSUE TITLE
Driver accepted match SMS notification doesn't include rider contact details

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/backend#111]
Please add rider contact details to SMS notification that the driver receives after confirming a match. We do not want to risk them forgetting to get in touch with the rider.

Please also do the same the other way around. I.e., send the rider the driver's contact details (in case there's an issue with the driver getting in touch).

**Comment by dmilet** [comment]
@sasjkia Please verify now

**Comment by sasjkia** [comment]
@dmilet all information appears as needed - thanks!
