### ISSUE TITLE
Add license driver license plate number to rider match confirmations

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/backend#117]
In the SMS and email notifications that the rider receives after a driver has confirmed a match, please add: "Please check the license plate number before getting in: xxxxxxxxx"

This is a safety feature, so the rider know they're getting in the right vehicle.

**Comment by dmilet** [comment]
OK I'll work on it

**Comment by dmilet** [comment]
@sasjkia Please verify now

**Comment by sasjkia** [comment]
@dmilet - works great - thanks!
