### ISSUE TITLE
Add ride details to proposed match SMS

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/backend#118]
Proposed match SMS notifications going to the driver does not currently contain the details of the ride. We'd like to driver to have an idea of whether the ride could work, before they log in (especially if they've already set up a few rides), so that unnecessary logins don't become a burden.

Please include in the proposed match notifications:
1. Dates and am/pm
2. Start and end zip
3. Power chair needed (only if yes)
4. Special accommodation notes (only if any)

**Comment by dmilet** [comment]
@sasjkia "Special accommodation notes " is potentially a large field. Are you sure you want it in the SMS ?

**Comment by dmilet** [comment]
And also, the corresponding e-mail going to the driver includes potentially multiple proposed matches.
I don't think we should overload the SMS.
That's why the SMS with match updates contains only a link to the self-service page.
Remember that only the self-service page reflects real time information.

**Comment by sasjkia** [comment]
@dmilet it is unlikely that the driver will log into the self-service page if they do not have an indication of whether it's worth their while. I guess we could leave accommodation notes for now but dates, times, and locations are a bare necessity.

**Comment by dmilet** [comment]
@sasjkia can you please check this SMS match notification going to the driver now?  I made a few changes,  but I can't test from here. Live environment.

**Comment by sasjkia** [comment]
@dmilet  it works on live site - thank you!

We'll need to work on formatting. of course.

**Comment by dmilet** [comment]
Let's bear in mind that SMS are plain text, and newline characters can be interpreted differently depending on carriers. It make any kind of formatting very difficult.
