### ISSUE TITLE
Allow drivers and riders to amend any of the ride or personal details in the self-service portal

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/backend#128]
On top-right of the main landing page in the self-service portal, include a button linking to “Modify details” page. On this page, include all of the information as recorded on the signup form. Allow modification of any of these details (except T&Cs).

Require user to click “Submit” button to save changes.
Prompt user to “Submit” or “Cancel” details if they try to leave after making changes without submitting.

This feature should relieve considerable pressure on the customer service team during election time.

**Comment by sasjkia** [comment]
@kylejcrawford

**Comment by jkbits1** [comment]
@sasjkia @richardwestenra @dmilet I understand the concerns behind this, but this change requires a new page. That new page will have to support all the behaviour of the add rider/driver pages. There will be backend work, too.

From the point of view of the driver and rider, they may have agreed to offer/accept a ride based on the original data provided. Currently, this situation can be managed by the rider or driver cancelling their offer/request and re-entering the info. True, they will cancel any agreed rides, but perhaps that is correct given my previous sentence.

**Comment by jkbits1** [comment]
@sasjkia the new operator focus of the system means this issue is less of a priority, so I'm closing. Re-open if you want later
