### ISSUE TITLE
Driver self-service portal perfect match says "Score: 0"

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/backend#130]
Unclear what this means, so probably also confusing for the driver

**Comment by dmilet** [comment]
Yes this needs to be cleanup up and removed from self service pages

**Comment by sasjkia** [comment]
Are we still doing the think where the Score 4 match shows up in the self-service portal but not notifications?

**Comment by dmilet** [comment]
We can
It's not done at the moment 
The "Score" doesn't have any real external meaning any more. Better remove it everywhere.
 
The match status attribute carries the right information 
MatchProposed goes to notifications
ExtendedMatch could be included in self service page

**Comment by dmilet** [comment]
@jkbits1 will you be able to remove references to "score" values in self-service page?

**Comment by jkbits1** [comment]
@dmilet one of our new contributors will be taking a look at this
