### ISSUE TITLE
Remove driver zip and radius from rider match confirmation SMS

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/backend#132]
The available times are useful to the rider but the assumption will be that they are within the radius (and they may find it confusing if they are a little out).

**Comment by dmilet** [comment]
radius never goes to the rider notifications, can you please confirm what you got ?

**Comment by sasjkia** [comment]
@dmilet can't see radius now but also can't see driver starting zip and available drive times (instead, the rider receives details of their own ride request in the SMS, which is unnecessary)

**Comment by sasjkia** [comment]
BTW - Formatting is much improved!!! :)

**Comment by jkbits1** [comment]
@sasjkia from reading the discussion above, it looks like this can be closed.
