### ISSUE TITLE
Confirming a match redirects to strange text

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/backend#137]
This is the case for all ride management links in emails. Please change the text to the following:

- [ ] 1
#### Driver accepts match
We have let [rider name] know that you have accepted their request for a ride. [Rider name] is now waiting for you to get in touch to arrange the details of the ride.

Please contact the rider as soon as possible via **[preferred contact method]**.

We have sent your an email [and SMS, if applicable] notification confirming this information. If you do not receive this, please contact customer support: 804-239-3389

- [ ] 2
#### Rider cancels specific ride match (NOT entire ride request)
We have let [Drive Name] know that you no longer need a ride from them. Our system will keep trying to find you a match.

Carpool Vote cannot guarantee that there will be another match, or that another driver will provide a ride as agreed. Please keep looking for a ride until you have reached your  destination.

If this was an error, please contact user support on 804-239-3389.

- [ ] 3
#### Rider cancels entire ride request
Your request for a ride has been cancelled. If you had already been matched with a driver, we've let the driver know that you no longer need a ride.

You can reactivate the request through the self-service portal [please include link to specific UUID login] or by calling 804-239-3389. You can also sign up again on CarpoolVote.com.

- [ ] 4
#### Driver confirms match but it's no longer available
Thank you for offering to help! This rider no longer needs a ride. We'll let you if anything changes.

- [ ] 5
#### Driver cancels specific ride match (NOT entire ride offer)
We have sent [Rider Name] a notification that you are no longer able to offer them a ride. If their preferred contact method was phone, we ask that you also let them know in this way, as our system does not currently support voice notifications.

Our system will keep trying to find the rider another match.

If you cancelled the ride offer in error, please contact rider to let them know.

**Comment by dmilet** [comment]
Nope
Fix is quite involved. It probably needs a redirect to the self service page.

**Comment by sasjkia** [comment]
@jkbits1 - maybe @russon77 can take this on?

We need the confirmation text to say something legible whenever someone manages a match through the emails (confirms, cancels etc). Underneath the explanatory text, there can be a self-service page login.

Someone needs to go through these and identify the actions that need this fix. I think it's all of them.

**Comment by jkbits1** [comment]
@sasjkia thanks for spotting this 👍  What system is this happening on (e.g. test or live) and what are the basic steps to reproduce, please? No need to spend ages on details, I don't think, just let me know the basic steps

**Comment by sasjkia** [comment]
I clicked  "Accept" link in proposed match email.

**Comment by jkbits1** [comment]
Thanks, I'll take a look

**Comment by sasjkia** [comment]
@jkbits1 this is also happening with all other email ride match actions. I'll document and add to this issue. :)

**Comment by sasjkia** [comment]
@kylejcrawford this is one of the issues that can get quite confusing for users.

**Comment by kylejcrawford** [comment]
@sasjkia So I understand...when you click "Accept" link in the email, it sends you to a page with weird text? Or they receive an email with the weird text?

**Comment by jkbits1** [comment]
@sasjkia I'm closing this as emails are likely to be simpler as the system focus shifts to the operator. It can be re-opened if necessary
