### ISSUE TITLE
Add full ride request details to self-service portal suggested and confirmed matches

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/backend#139]
Please:
- [ ] Available ride times
- [ ] Add "(preferred)" next to the preferred contact method; remove this from the line containing the accommodation notes
- [ ] Add power chair adapted vehicle needed, where this applies
- [ ] Add number of seats required
- [ ] Specify whether 2-way trip is needed

Also separate SMS and notes into 2 separate lines (currently they appear next to each other, and look squashed/confusing)

**Comment by jkbits1** [comment]
Fixed by https://github.com/voteamerica/voteamerica.github.io/pull/422
