### ISSUE TITLE
Can we version the API (such that we could have two versions potentially in use at the same time?)

### ISSUE THREAD

**Issue by misteranderson** [voteamerica/backend#14]
Something like:

https://api.carpoolvote.com/v1.0/drivers/
https://api.carpoolvote.com/v1.1/drivers/

https://api.carpoolvote.com/v1.0/riders/
https://api.carpoolvote.com/v1.1/riders/

https://api.carpoolvote.com/v1.0/helpers/
https://api.carpoolvote.com/v1.1/helpers/

https://api.carpoolvote.com/v2.0/zipcodelookup/

I suspect this would be multiple versions of the node app, running concurrently, in different directories, on different ports, and then nginx handling the routing from /v1.0/* to one port, and /v2.0/* to another port?

**Comment by dmilet** [comment]
Do you think we'd need corresponding versions of the stage tables?

**Comment by dmilet** [comment]
We have it in place now, though I have been manually updating v1.1 for the demo, as well as v2.0. Version selection requires changing code in index.html, but at least it's working

**Comment by jkbits1** [comment]
that seems a perfectly reasonable solution

**Comment by dmilet** [comment]
no need to keep this open
