### ISSUE TITLE
Rider SMS notification criteria needs to be modified

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/backend#144]
**It appears that the rider SMS notification user story still reflects an old version of the user form.** Currently:
- Riders receive SMS notifications only if they have specified that they want to be contacted via SMS (the signup form text has been updated to specify that this is the preferred method of contact from the driver)

**The issues here are:**
- The SMS notification will still go out if the rider has input a landline number; it doesn't make sense to spend this money if the rider isn't going to receive the SMS notification. And drivers may text riders when there is no way for them to get hold of them this way.
- Riders who wish to be contacted via phone may not have regular internet access. If they have input a cell phone number, SMS notifications may be better than email notifications.

**With this in mind, please can we update criteria determining when riders receive SMS notifications, to reflect the following:**
- [ ] If the rider says they prefer the drivers to contact them by SMS OR by phone, and the rider has input a cell phone number, the rider receives SMS notifications.

[Issue #281](https://github.com/voteamerica/voteamerica.github.io/issues/281) on the front end deals with preventing contradicting input from the rider.

**Comment by sasjkia** [comment]
@jkbits1 @dmilet @richardwestenra I think this one will take some coordination between frontend and backend.

**Comment by richardwestenra** [comment]
btw I noticed recently that we added a form checkbox for users to indicate whether their phone number is a mobile. However it might be possible to do it programmatically instead, and avoid users having to specify. Twilio provide and API for this: https://www.twilio.com/lookup

**Comment by sasjkia** [comment]
@richardwestenra that would be ideal! @dmilet is this something we can do from the backend?

**Comment by dmilet** [comment]
As per twilio, checking connection type (landline vs mobile I guess) is chargeable. Do we want to do this with every phone number?

There are voip solutions that allow for SMS, and also carriers which are replacing landlines as fast as they can with voip without telling their customers.

Maybe we should have two input fields, one for home phone, one for mobile phone, with the assumption that mobile phone can receive SMS when the home phone cannot?
Otherwise, the checkbox to indicate a mobile phone is good enough I think

**Comment by sasjkia** [comment]
@dmilet let's keep this on the frontend for now, then. We do say that cell phones are preferred, so hopefully this is enough. Perhaps @kylejcrawford has a UX view on this?

@dmilet please could the number one priority right now be to ensure that rider phone number and email address details do not go to the driver before they have accepted the match?

**Comment by dmilet** [comment]
Looking at code for outbound notifications, I don't see RiderPhone or RiderEmail being sent to the Driver until after the driver accepts the match
Can you please confirm where you're seen it?

**Comment by sasjkia** [comment]
Thanks for checking @dmilet. What about through email notifications? I got one with these details just a few days ago.

**Comment by dmilet** [comment]
I don't see any

**Comment by kylejcrawford** [comment]
I'll set up a rider and driver match to see how things are looking currently. 

And I'll use that experience to think through the phone number input issue a bit more, and report back.

**Comment by jkbits1** [comment]
@sasjkia I'm closing this. SMS messages are being sent using the twilio non-profit support amount and the developer/design time is needed elsewhere. This issue can be re-opened if this situation changes
