### ISSUE TITLE
Change wording for notification SMS when rider cancels ride request

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/backend#145]
Please change to text to the following:

> From Carpool Vote to [name] [ref].
Your ride request has been canceled. You will no longer be matched with a driver for the following dates/times: [includes dates and times only].
You can reactivate your ride request through the self-service portal [include link] or by calling/texting 540-656-9388

This issue is linked to backend [issue #282.](https://github.com/voteamerica/voteamerica.github.io/issues/282)

**Comment by jkbits1** [comment]
@sasjkia I'm closing as the system focus around operators means work on emails is less of a priority. We can re-open later if you want
