### ISSUE TITLE
Update SMS notification text for ride request received

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/backend#147]
Different rules seem to apply for formatting different parts of the text message (underlining specifically). Wording can also be a little clearer in places. Please change to the following (**bold**=underlined):

> From Carpool Vote to [name] [ref].
Ride request received!
Preferred ride times: **mmm d, yyyy, hh:mmam/pm-hh:mmam/pm**; **mmm d, yyyy, hh:mmam/pm-hh:mmam/pm**
Pick up: **Address**
Destination: **Address**
Seats needed: **#**
Power chair adapted van needed? **Yes/No**
Two-way trip needed? **Yes/No**
Notes: **xxx**
Phone: **###-###-####** (cell/landline)
Email: **xxx@xxx.xxx**
Preferred contact: **SMS/phone/email**
To manage your ride request, please visit our **self-service portal [link]** or call user support on **540-656-9388**.

Is there a way to shorten the self-service portal link that we send them. They tend to be a bit unruly and take up quite a lot of space...

Please remove Cancellation link. We had problems with accidental link clicking in the text messages last year. Worst-case scenario is that the riders are contacted multiple times and have to cancel through the phone line. They wouldn't be able to click the link anyway, if they didn't have internet access. And they could always cancel through the self-service portal if they did.

**Comment by sasjkia** [comment]
@kylejcrawford links in the text messages are an ongoing discussion. What do we include? How do we format them?

**Comment by jkbits1** [comment]
@sasjkia I'm closing as the system focus around operators means work on emails is less of a priority. We can re-open later if you want
