### ISSUE TITLE
Strange error message

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/backend#159]
Not sure what caused this, and I can't replicate. Does this mean we're able to submit a form with a problematic radius?

![image](https://cloud.githubusercontent.com/assets/19363959/26708290/f0deed22-4718-11e7-93aa-30172520d32e.png)

**Comment by sasjkia** [comment]
cc @richardwestenra

**Comment by sasjkia** [comment]
Looks like "0" is considered invalid input for driver radius

**Comment by dmilet** [comment]
valid range : 0 < radius < 100

Let me know if I need to change that
Last time we discussed this, we said a radius of 0 makes no sense

**Comment by sasjkia** [comment]
Radius of 0 implies only within the zip code, so would be good to change at some point but this is not a priority right now.
