### ISSUE TITLE
Email links allow for multiple cancellations of ride request

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/backend#161]
When a rider clicks the "Cancel this ride request" link in the email notification, they receive email/email and SMS notifications.

When the click the link again, they receive the same notifications. This goes on and on. It is unclear whether the request has actually been canceled or not.

**Comment by dmilet** [comment]
I can reject Cancel requests in case the status is already Cancel or Expired
But not today, not if you have a demo soon
I'm too jetlagged to trust what I write today

**Comment by jkbits1** [comment]
@sasjkia I've tested this and the email seems clear now that the request has been cancelled. There are multiple emails but this doesn't seem unreasonable. 

I'm closing this. However, as the test system doesn't seem to be sending emails, I'm presuming this behaviour is occurring based on the db entries. If that is incorrect, or you feel that multiple emails are unhelpful, please re-open or open a new issue
