### ISSUE TITLE
Driver is receives proposed match from rider after the rider has cancelled the ride request

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/backend#166]
![image](https://user-images.githubusercontent.com/19363959/26837989-e04b9202-4aac-11e7-971a-30cc4b304d88.png)

**Comment by sasjkia** [comment]
This is a bit of an issue for the demo because it's impossible to test any rider-driver set... even if you cancel the ride request, the driver's next proposed match email will contain 2 of the same address 😱

**Comment by jkbits1** [comment]
@sasjkia probably a bit tricky to patch this in time for the demo 😞

**Comment by dmilet** [comment]
what time is the demo?
I have a fix

**Comment by dmilet** [comment]
fix is on test environment, I can load it on live if you can confirm your
demo scenario works on test

**Comment by jkbits1** [comment]
@sasjkia @dmilet fix looks good

**Comment by gmisura** [comment]
This still open?

**Comment by jkbits1** [comment]
@gmisura hi there, thanks for the interest @sasjkia @dmilet is this still an issue?

**Comment by jkbits1** [comment]
@gmisura I think this has been resolved.

You are welcome to take a look at https://github.com/voteamerica/backend/issues/163
Bear in mind that issues like these involve the entire system. Sometimes the issue isn't totally clear whether it's web page or email/sms issue. The docker setup doesn't send emails or sms messages, so these issues involve looking at the db tables for "outgoing_email" and "outgoing_sms"

Let me know if I can assist in any way
