### ISSUE TITLE
Provide docker setup to deploy on new DO VM

### ISSUE THREAD

**Issue by dmilet** [voteamerica/backend#198]
New DO VM needs to be deployed
Docker containers will be used for backend elements

**Comment by dmilet** [comment]
https://github.com/voteamerica/backend/pull/196

**Comment by dmilet** [comment]
docker setup is available

**Comment by jkbits1** [comment]
@dmilet this is great work 🎉 I only noticed yesterday this issue was still open after the PR was merged but didn't close in case you had other steps planned
