### ISSUE TITLE
operator table not aligned with submit_new_user function 

### ISSUE THREAD

**Issue by dmilet** [voteamerica/backend#206]
--
-- Name: operator; Type: TABLE; Schema: carpoolvote; Owner: carpool_admins
--

CREATE TABLE operator (
    "UUID" character varying(50) DEFAULT gen_random_uuid() NOT NULL,
    "email" character varying(250) NOT NULL,
    "username" character varying(250) NOT NULL,
    "password" character varying(250) NOT NULL,
    "admin" boolean NOT NULL,
    "UUID_organization" character varying(50)
);

But in submit_new_user, the table columns are different:
BEGIN			
		out_uuid := carpoolvote.gen_random_uuid();
		
		INSERT INTO carpoolvote.operator(
		"UUID", "email", "username", "userpassword", "userIsAdmin")
		VALUES (
		out_uuid, email, username, userpassword, userIsAdmin
		);
			
		RETURN;
	EXCEPTION WHEN OTHERS
	THEN
		out_uuid := '';
		out_error_code := carpoolvote.f_EXECUTION_ERROR();
		out_error_text := 'Unexpected exception in submit_new_user, ' || v_step || ' (' || SQLSTATE || ')' || SQLERRM;
		RETURN;
	END;

**Comment by dmilet** [comment]
@jkbits1   Jon, I think we should rename the function submit_new_user to submit_new_operator and align with the table. 
What values do you pass from the front end ?

**Comment by dmilet** [comment]
would tb_user be ok ? It will be transparent to you as I'll update the submit_new_user function as well


LIVE=# \d+ carpoolvote.tb_user;
                                                  Table "carpoolvote.tb_user"
      Column       |          Type          | Collation | Nullable |      Default      | Storage  | Stats target | Description
-------------------+------------------------+-----------+----------+-------------------+----------+--------------+-------------
 UUID              | character varying(50)  |           | not null | gen_random_uuid() | extended |              |
 email             | character varying(250) |           | not null |                   | extended |              |
 username          | character varying(250) |           | not null |                   | extended |              |
 password          | character varying(250) |           | not null |                   | extended |              |
 is_admin          | boolean                |           | not null | false             | plain    |              |
 UUID_organization | character varying(50)  |           |          |                   | extended |              |
Indexes:
    "user_pk" PRIMARY KEY, btree ("UUID")
Foreign-key constraints:
    "user_uuid_organization_fkey" FOREIGN KEY ("UUID_organization") REFERENCES organization("UUID") ON DELETE CASCADE

**Comment by jkbits1** [comment]
@dmilet that sounds great, thanks 👍 if you create a PR for that, I'll either merge it when I see it or you can simply merge it straight away

**Comment by jkbits1** [comment]
@dmilet looks like we tidied up everything we needed to, so closing this
