### ISSUE TITLE
ip address logged in stage tables is always 127.0.0.1

### ISSUE THREAD

**Issue by dmilet** [voteamerica/backend#23]
Is this because it's all proxied by nginx ?

**Comment by misteranderson** [comment]
https://www.digitalocean.com/community/tutorials/understanding-nginx-http-proxying-load-balancing-buffering-and-caching seems to be a useful resource for this.

**Comment by misteranderson** [comment]
We should be able to close this - there are non-localhost IP addresses in the staging tables now.

**Comment by jkbits1** [comment]
thanks @misteranderson
