### ISSUE TITLE
Rider/Driver submissions from form fails if some non-required boxes are not checked.

### ISSUE THREAD

**Issue by misteranderson** [voteamerica/backend#31]
For Example:

rider row insert failed: null value in column "TwoWayTripNeeded" violates not-null constraint.

What should happen:
The backend node app should check for existence / provide default (false/0) values for the data elements which are being inserted.

Those include:
DrivingOnBehalfOfOrganization (default false)
WheelchairCount (default 0)
NonWheelchairCount (default 0)
TwoWayTripNeeded (default false)
DriverEmailValidated (default 0/false?, until validated by confirming/responding to Email.)
DriverPhoneValidated (default 0/false, until validated by confirming/responding to Text.)
ReadyToMatch (default 0)
PleaseStayInTouch (default 0)

**Comment by jkbits1** [comment]
@misteranderson are we sure these defaults are valid? That's part of the reason I don't sanitise data received from the client. 
How is it possible for the client not to send these values? I'm concerned about the situation where driver/rider enters details and these are not sent, and the defaults are incorrect.
A failure is inconvenient, but better than a result that reports success but is in reality wrongly stored

**Comment by misteranderson** [comment]
Well, the results don't actually get inserted into the staging table (so we're not reporting success and storing incorrect values), but the error message is not helpful to the user - if they don't need a two-way ride, and therefore haven't checked the box,, then the form isn't sending that field.

**Comment by dmilet** [comment]
there were some xhtml syntax errors that caused the form to not submit some fields especially some checkboxes. If this is still happening, it may be because old code was re-introduced with the same bug.
In short, always close the xml tags <input ... />  and the value=xxx should not be present. 

The form normally always sends true/false value for all checkboxes, whether checked or not

**Comment by jkbits1** [comment]
It doesn't seem to be the xhtml this time. 
If it isn't resolved by the front-end team I'll apply defaults in the node app for short term purposes

**Comment by dmilet** [comment]
Just put in a PR to fix this issue.

**Comment by dmilet** [comment]
I think we can close this issue now

**Comment by jkbits1** [comment]
agreed
