### ISSUE TITLE
index.js - store driver license number

### ISSUE THREAD

**Issue by dmilet** [voteamerica/backend#36]
I see that the driver form now has field for Driver License Number

index.js should now be able to insert it too 

Here is the corresponding field in the DB
DriverLicenseNumber              | character varying(50)       |                  

And VehicleRegistrationNumber is gone now I think, can be removed from index.js

**Comment by jkbits1** [comment]
left deletion of vehicle reg num until after demo

**Comment by dmilet** [comment]
VehicleRegistrationNumber  is removed from 2.0 schema
