### ISSUE TITLE
Index.js to implement GET API for geo map data

### ISSUE THREAD

**Issue by dmilet** [voteamerica/backend#43]
Goal is to map unmatched riders

The first phase would be a simple descriptive map of current unmatched driver / rider locations so a simple table would be fine of lat, long, zip, and count, example here: https://github.com/voteamerica/voteamerica.github.io/tree/master/carpool-map/data

I'll provide a view stage.vw_unmatched_riders with the information collected from websumbission_rider and zip_codes tables

**Comment by jkbits1** [comment]
will take a look at this

**Comment by dmilet** [comment]
Here is the view, created on carpool.dev for now.
Let me know if it matched what we need

[carpool_web@CentOS72 nodeAppPostPg]$ psql -h /tmp carpool.dev
psql (9.5.4)
Type "help" for help.

carpool.dev=> select * from stage.vw_unmatched_riders;
 count |  zip  | state |  latitude  | longitude  |    city     | full_state | latitude_numeric | longitude_numeric |               latlong                
-------+-------+-------+------------+------------+-------------+------------+------------------+-------------------+--------------------------------------
   270 | 11780 | NY    |  40.884394 |  -73.15868 | Saint James | New York   |          40.8844 |          -73.1587 | (40.8843955993652,-73.1586837768555)
(1 row)

**Comment by jkbits1** [comment]
addressed by https://github.com/voteamerica/backend/pull/46

requires review, no data at time of coding

**Comment by jkbits1** [comment]
see this for guidance/example on using API https://github.com/voteamerica/backend/pull/48

**Comment by dmilet** [comment]
I believe this issue can be closed.
