### ISSUE TITLE
unmatched drivers json has duplicate lat/lon information

### ISSUE THREAD

**Issue by dmilet** [voteamerica/backend#55]
[{"count":"1","zip":"20111","state":"VA","latitude":" 38.769697","longitude":" -77.44915","city":"Manassas","full_state":"Virginia","latitude_numeric":38.7697,"longitude_numeric":-77.4492,"latlong":{"x":38.7696952819824,"y":-77.4491500854492}}]

**Comment by langdonms** [comment]
We only need one, I would opt for the numeric and we can always reconvert it to a string it if we need to.

**Comment by jkbits1** [comment]
if this refers to the returned values from the api, the node app simply returns the rows from the relevant db view

**Comment by dmilet** [comment]
Removed extra information from the view 
@langdonms please close this issue if it works for you.

[{"count":"1","zip":"28633","state":"NC","city":"Lenoir","full_state":"NC","latitude_numeric":35.9,"longitude_numeric":-81.53},{"count":"1","zip":"60010","state":"IL","city":"Barrington","full_state":"Illinois","latitude_numeric":42.142,"longitude_numeric":-88.1773}]

**Comment by dmilet** [comment]
Merged already. Issue is fixed
