### ISSUE TITLE
What do we do against SQL injection? 

### ISSUE THREAD

**Issue by dmilet** [voteamerica/backend#58]
We have a few text fields, which will be displayed in the self-service page, and email. 
Also the same text fields are used in APIs to manage the ride requests/driver offers.

What should we do against SQL injection ?

**Comment by misteranderson** [comment]
We (are/should be) using parameterized SQL queries (?,?,?) rather than composing the SQL based on unsanitized input. Certainly a review of all SQL statements is in order to be sure.

**Comment by misteranderson** [comment]
Are you really talking about SQL Injection (having the database do something the attacker wants/we didn't intend), or cross-site scripting / injecting javascript or other browser scripting into the fields which are displayed when we get the values out of the database?

**Comment by dmilet** [comment]
Well for cancel and confirm operations, we verify that the uuid matches with the last name of the person. The node app calls a function in the database which does equality comparison in pl/pgsql. I wonder if someone would be able to bypass that check on last name and potentially cancel any uuid.

The 2nd concern indeed is cross site scripting because we have that Notes field which we display back in the HTML email and surely also on the self service page.

Who should be sanitizing the input? The node app or the db? And I'm not sure how to do it on the db either, I'd need advice to do it right.

**Comment by jkbits1** [comment]
@dmilet for your first point, I generally feel confident when the sql is in a function that it's harder to get it to behave incorrectly. Still, the text does not get checked that much currently before the function goes to work on it

**Comment by dmilet** [comment]
Let's close this one.
We don't need to do anything about it
