### ISSUE TITLE
Pause Match Driver feature

### ISSUE THREAD

**Issue by dmilet** [voteamerica/backend#62]
@jkbits1 See new USER STORY 016
I'll have the procedure ready soon. 
And I need to update a few e-mail notifications to include the new link

**Comment by dmilet** [comment]
New procedure is in carpool_v2.0_test and carpool_v2.0_live databases

**Comment by jkbits1** [comment]
@dmilet is this is supported now by the db? it is built into the node app and the self service page. if so, we can close this issue

**Comment by dmilet** [comment]
carpoolvote.driver_pause_match(UUID, phone number or lastname ?, OUT out_error_code INTEGER, OUT out_error_text TEXT)

Closing issue
