### ISSUE TITLE
zip code 20021 is no in zip_codes table

### ISSUE THREAD

**Issue by dmilet** [voteamerica/backend#71]
to be investigated.
A rider record on live environment failed because of this

**Comment by dmilet** [comment]
This is a Washington, DC zip code.

**Comment by dmilet** [comment]
@misteranderson do you want to take a look at this ? 
We could add it manually to the database, then change the state of the record to "Pending"

**Comment by misteranderson** [comment]
I will take a look.

**Comment by misteranderson** [comment]
I do not see the data about this zip code in the source file. I have a hard time locating information about this zip code in google searches. Are we sure it is a valid ZIP code (and do we have an address we can use for looking up more info, to try and get a good lat/long for it?

In fact, entering Washington DC, 20021 into the USPS ZIP code lookup tool gives 20020 and 20022 (among many others) but nothing for 20021.

**Comment by misteranderson** [comment]
![2016-10-25 22_33_24-start](https://cloud.githubusercontent.com/assets/1386657/19712433/6c13951e-9b03-11e6-9ce9-55e606184fd0.png)

**Comment by dmilet** [comment]
Weird...
http://www.phe.gov/Preparedness/planning/cip/Documents/hph-joint-mtg-logistics20150305.pdf
https://www.noodle.com/schools/ktQk9Q/kipp-dc-heights-academy-public-charter-school

**Comment by dmilet** [comment]
no action to take for this particular driver, it was just a test
carpool_v2.0_live=> select "UUID", state, "RiderAccommodationNotes" from stage.websubmission_rider where state='Failed';
                 UUID                 | state  |                                      RiderAccommodationNotes
--------------------------------------+--------+----------------------------------------------------------------------------------------------------
 900d9e6b-32d7-4363-8ef6-83827b940db6 | Failed | This is just a technical/website test. NOT an actual booking. Please DISCARD this booking request.
