### ISSUE TITLE
user action link return json object when clicked from an e-mail

### ISSUE THREAD

**Issue by dmilet** [voteamerica/backend#72]
For example, for accepting a match,
@jkbits1  Is there a way to return a plain string maybe to confirm success. Right now, it only returns the name of the action and an empty string.
It works, but it does not look nice.

**Comment by jkbits1** [comment]
@dmilet both email and self service page use the same mechanism, so they have to line up

the empty string is return by the db function. why not put a success message there? I show it on the self service page

**Comment by dmilet** [comment]
@jkbits1 @sasjkia I think the links in email notification should redirect to the self service page, not perform action directly
It's too easy on a smartphone to accidentally click on a clink 
We had issues last year where matches were canceled, and the user claimed they don't recall canceling them 
We should focus on improving the self service page as central place for the user to jntrleract with our system

**Comment by sasjkia** [comment]
@dmilet This was resolved when we removed the links from text messages. I don't want to add an extra barrier to accepting matches. I think it's better for the links to stay for now. We can review after the primaries. Is there a way for people to confirm matches by responding to an email with a "yes"?

**Comment by sasjkia** [comment]
But you're right that we need to improve the UX of the confirmation messages.

**Comment by dmilet** [comment]
I like the way it's done for the new submissions (with thank you page)
Maybe user actions to manage matches need to be redirected to a results page? 
Right now the self-service page displays the results within the same page, which is typically something like (0,"","") in case of success.
When the "Accept" link is clicked from an e-mail, the user's browser will display the same thing on a blank page.

**Comment by jkbits1** [comment]
@dmilet I'm tempted to close this as the system is planned to be more focused on operators and less on drivers/riders receiving emails. On the other hand, the system still sends emails and they seem useful
