### ISSUE TITLE
To Investigate why the counts don't add up

### ISSUE THREAD

**Issue by dmilet** [voteamerica/backend#89]
I can't explain why we have 207 matches in state MatchConfirmed, but only 57 riders in that state.
Normally, there is one match per rider at most

Report run on Tue Nov  8 12:00:01 UTC 2016
carpool_v2.0_live
DRIVERS
 count |     state
-------+----------------
   250 | Canceled
   935 | Pending
   448 | MatchProposed
   138 | MatchConfirmed
   613 | Expired
    33 | Failed
(6 rows)

RIDERS
 count |     state
-------+----------------
    31 | Canceled
     6 | Pending
    57 | MatchConfirmed
     6 | MatchProposed
    18 | Expired
    16 | Failed
(6 rows)

MATCHES
 count |     state
-------+----------------
   800 | Canceled
   946 | MatchProposed
   207 | MatchConfirmed
(3 rows)

EMAILS
 count | state
-------+--------
  4940 | Sent
   703 | Failed
(2 rows)

SMS
 count | state
-------+--------
  3040 | Sent
    52 | Failed
(2 rows)

**Comment by sasjkia** [comment]
@dmilet this is because there have been multiple notifications for the same drivers

**Comment by jkbits1** [comment]
@dmilet @sasjkia I've created a couple of db queries to turn this data into actual users. Let me know if it's helpful for you to know more about these
